name: Build and Deploy Docs
'on':
  push:
    branches:
      - development
jobs:
  build_and_deploy_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd sources && npm install
      - run: cd sources && npm run doc
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PROJECT_ELAICHI }}'
          channelId: live
          projectId: project-elaichi
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
